### ISSUE TITLE
Sayfa içeriği eksik

### ISSUE THREAD

**Issue by yy34** [javascript-tutorial/tr.javascript.info#156]
Merhaba 

[bu](https://tr.javascript.info/dom-nodes) sayfa doğru olarak birleştirilememiş ve bozuk görünüyor 

alttaki konuda gerekli dosyalar mevcut

https://github.com/javascript-tutorial/tr.javascript.info/pull/148

**Comment by sahinyanlik** [comment]
Merhaba,

Yardımlarınız için teşekkürler. İncelediğimde bazı tırnak işaretlerinde problemler gördüm. Özellikle yazmamaya başladığı noktadan incelerseniz siz de görebilirsiniz.  Bu tırnak işaretleri düzeldiğinde problem düzelecektir.

**Comment by sahinyanlik** [comment]
Tırnak işaretleri düzeltilmiştir. Sayfa düzgün görünmekte.
