### ISSUE TITLE
Kırık Linkler

### ISSUE THREAD

**Issue by fatmabadri** [javascript-tutorial/tr.javascript.info#181]
Bu mesaj maintainers icin:
@sahinyanlik , @aliemir, @bilgedemirkaya 

Üzerinde çalıştığım klasörü çevirmeyi bitirdim. Diğer alınmamış ilk sıralardaki klasörleri kontrol ettiğimde, linkler hata veren bir sayfaya açılıyor. Repoda kırık linkler var.

https://github.com/javascript-tutorial/tr.javascript.info/blob/master/1-js/02-first-steps/12-nullish-coalescing-operator
https://github.com/javascript-tutorial/tr.javascript.info/blob/master/1-js/02-first-steps/16-function-expressions
https://github.com/javascript-tutorial/tr.javascript.info/blob/master/1-js/05-data-types/08-weakmap-weakset
https://github.com/javascript-tutorial/tr.javascript.info/blob/master/1-js/06-advanced-functions/02-rest-parameters-spread

Bu arada hatırlatmak istiyorum, lütfen  <strong>'modifying document'</strong>i onaylar mısın? Çünkü çevirisi tamamlandı.
Buradan erişebilirsiniz: https://github.com/javascript-tutorial/tr.javascript.info/issues/1

Sayfadaki yeri:
<strong>Browser: Document, Events, Interfaces </strong>bölümünde
    -Document
      --Modifying the document

Teşekkür ederim.

**Comment by bilgedemirkaya** [comment]
Modifying the document onayladim, comment kismina basligi ayni sekilde kopyala-yapistir yaparsan bot onaylar cevirdigin kisimlari

**Comment by bilgedemirkaya** [comment]
Kirik linkleri duzelttim, ancak klasorlerde kayip bir kac konu var, @sahinyanlik  @aliemir bunun icin ayri issue aciyorum.
