### ISSUE TITLE
info:type-conversation makalesi bulunamadı

### ISSUE THREAD

**Issue by cengizcmataraci** [javascript-tutorial/tr.javascript.info#270]
Selam, emekleriniz için çok teşekkürler.
Koşul Operatörleri Boolean Dönüştürme sayfasında type-conversation makalesi yerinde ""type-conversation" adresindeki makale bulunamadı" yazıyor. Muhtemelen bu makalenin adı değişti ya da kaldırıldı. 
![image](https://user-images.githubusercontent.com/13690848/163724557-676ec75e-2fd6-4938-8c5c-e92b138456ae.png)

**Comment by sahinyanlik** [comment]
Merhabalar,
Düzenleme yapıldı
