### ISSUE TITLE
Example domains

### ISSUE THREAD

**Issue by nilgun** [javascript-tutorial/tr.javascript.info#306]
tr.javascript.info/1-js/01-getting-started/1-intro/article.md
dosyasında
"Tarayıcı içerisinde bulunan JavaScript ne yapamaz?"
başlığı altında bazı alan adları görüyorum. Belgelerde kullanılmak üzere ayrılmış alan adları var. Bunları kullanın, böylece gereksiz yere kimsenin reklamını yapmamış olursunuz. Bu konuda asıl kaynağından bilgi almak için 
https://www.iana.org/domains/reserved
adresini ziyaret edin.

**Comment by sahinyanlik** [comment]
Merhabalar düzeltilmiştir.
