### ISSUE TITLE
Son durum

### ISSUE THREAD

**Issue by thealiyasar** [javascript-tutorial/tr.javascript.info#335]
Merhaba,
son durum hakkında bir güncelleme yapılmamış ve çoğu üstlenilen bölümler güncellenmemiş. Projenin çevirisi konusunu rafa mı kaldırdınız?

**Comment by sahinyanlik** [comment]
Merhabalar, 

Çoktandır pull request yapılmıyor. Ben de uzun süredir bu konuda zaman bulup çeviri yapamıyorum. Sizin geliştirmek istediğiniz bir bölüm var mı?

**Comment by thealiyasar** [comment]
Evet çevrisi yapılmayan yada üstlenipte hiç ilgilenilmeyen kısımlar için çeviri yapma niyetim bulunmakta. Lakin yönergeleri çok anlayamadım, anlatırsanız nasıl üstlenip yollayacağımı kısa zaman içinde bir parçayı çevirip denemesini yapabilirim.
